// packages/vue/src/elements/Button.vue
<script setup lang="ts">
import { computed } from "vue";

import type {
  ButtonProps,
  ButtonEvents,
  ButtonSize,
} from "@paraxe/core";

const props = withDefaults(
  defineProps<ButtonProps>(),
  {
    variant: "primary",
    size: "medium",
    width: "auto",
    iconPosition: "leading",
    disabled: false,
    loading: false,
  },
);

type ButtonEmits = {
  activate: [];
};

const emit = defineEmits<ButtonEmits>();

const sizeClasses: Record<
  ButtonSize,
  string
> = {
  small: "btn-sm",
  medium: "btn-md",
  large: "btn-lg",
};

const buttonClasses = computed(() => [
  `btn-${props.variant}`,
  sizeClasses[props.size],
  props.width === "full"
    ? "btn-full"
    : "",
]);
</script>

<template>
  <button
    class="btn"
    :class="buttonClasses"
    :disabled="props.disabled || props.loading"
    @click="emit('activate')"
  >
    <slot />
  </button>
</template>

// packages/react/src/elements/Button.tsx
import type { ButtonProps } from "@paraxe/core";
import type { ReactNode } from "react";
export type ButtonComponentProps = ButtonProps & {
  children?: ReactNode;
  onActivate?: () => void;
};
export function Button({
  variant = "primary",
  size = "medium",
  width = "auto",
  disabled = false,
  loading = false,
  onActivate,
  children,
}: ButtonComponentProps) {
  return (
    <button
      className={`btn btn-${variant} btn-${size}${width === "full" ? " btn-full" : ""}`}
      disabled={disabled || loading}
      onClick={() => onActivate?.()}
    >
      {children}
    </button>
  );
}
