// packages/react/src/primitives/Container.tsx
import type { ContainerProps } from "@paraxe/core";
import type { ReactNode } from "react";
export function Container({
  size = "default",
  children,
}: ContainerProps & { children?: ReactNode }) {
  return (
    <div className={size === "narrow" ? "container-narrow" : "container"}>
      {children}
    </div>
  );
}

// packages/vue/src/primitives/Container.vue
<script setup lang="ts">
import { computed } from "vue";
import type { ContainerProps } from "@paraxe/core";

const props = withDefaults(
  defineProps<ContainerProps>(),
  {
    size: "default",
  },
);

const containerClasses = computed(() => ({
  container: props.size === "default",
  "container-narrow": props.size === "narrow",
}));
</script>

<template>
  <div :class="containerClasses">
    <slot />
  </div>
</template>
