// packages/vue/src/data/EmptyState.vue
<script setup lang="ts">
import { computed } from "vue";
import type { EmptyStateProps } from "@paraxe/core";

const props = withDefaults(defineProps<EmptyStateProps>(), {
  as: "div",
});

const classes = computed(() => [
  "empty-state",
]);
</script>

<template>
  <component
    :is="props.as"
    :class="classes"
  >
    <div
      v-if="$slots.icon"
      class="empty-state-icon"
    >
      <slot name="icon" />
    </div>

    <div class="empty-state-content">
      <slot />
    </div>

    <div
      v-if="$slots.actions"
      class="empty-state-actions"
    >
      <slot name="actions" />
    </div>
  </component>
</template>

// packages/react/src/data/EmptyState.tsx
import type { EmptyStateProps } from "@paraxe/core";
import type { ReactNode } from "react";
export function EmptyState({
  as = "div",
  icon,
  actions,
  children,
}: EmptyStateProps & {
  icon?: ReactNode;
  actions?: ReactNode;
  children?: ReactNode;
}) {
  const Tag = as as keyof React.JSX.IntrinsicElements;
  return (
    <Tag className="empty-state">
      {icon ? <div className="empty-state-icon">{icon}</div> : null}
      <div className="empty-state-content">{children}</div>
      {actions ? <div className="empty-state-actions">{actions}</div> : null}
    </Tag>
  );
}
