// packages/vue/src/data/ListItem.vue
<script setup lang="ts">
import {
  computed,
  inject,
} from "vue";

export interface ListItemProps {
  value: string | number;
  disabled?: boolean;
}

const props = withDefaults(
  defineProps<ListItemProps>(),
  {
    disabled: false,
  },
);

interface ListContext {
  selectable: boolean;
  multiple: boolean;

  isSelected: (
    value: string | number
  ) => boolean;

  toggleSelection: (
    value: string | number
  ) => void;
}

const injectedList = inject<ListContext>("loba-list");

if (!injectedList) {
  throw new Error(
    "ListItem must be used inside a List.",
  );
}

const list = injectedList;

if (!list) {
  throw new Error(
    "ListItem must be used inside a List.",
  );
}

const isSelected = computed(() =>
  list.isSelected(props.value),
);

const classes = computed(() => ({
  "list-item": true,
  "list-item--selectable":
    list.selectable && !props.disabled,
  "list-item--selected":
    isSelected.value,
  "list-item--disabled":
    props.disabled,
}));

function handleClick() {
  if (
    props.disabled ||
    !list.selectable
  ) {
    return;
  }

  list.toggleSelection(props.value);
}
</script>

<template>
  <div
    :class="classes"
    :tabindex="
      list.selectable && !props.disabled
        ? 0
        : undefined
    "
    :aria-selected="
      list.selectable
        ? isSelected
        : undefined
    "
    :aria-disabled="
      props.disabled || undefined
    "
    role="listitem"
    @click="handleClick"
    @keydown.enter="handleClick"
    @keydown.space.prevent="handleClick"
  >
    <slot />
  </div>
</template>

// packages/react/src/data/ListItem.tsx
import type { ListItemProps } from "@paraxe/core";
import type { ReactNode } from "react";
import { useList } from "./List";
export function ListItem({
  value,
  disabled = false,
  children,
}: ListItemProps & { children?: ReactNode }) {
  const list = useList();
  if (!list) throw new Error("ListItem must be used inside a List.");
  const selected = list.isSelected(value);
  const interactive = list.selectable && !disabled;
  const handle = () => interactive && list.toggleSelection(value);
  return (
    <div
      className={`list-item${interactive ? " list-item--selectable" : ""}${selected ? " list-item--selected" : ""}${disabled ? " list-item--disabled" : ""}`}
      tabIndex={interactive ? 0 : undefined}
      aria-selected={list.selectable ? selected : undefined}
      aria-disabled={disabled || undefined}
      role="listitem"
      onClick={handle}
      onKeyDown={(e) => {
        if (e.key === "Enter" || e.key === " ") {
          e.preventDefault();
          handle();
        }
      }}
    >
      {children}
    </div>
  );
}
