// packages/react/src/forms/Textarea.tsx
import type { TextareaProps } from "@paraxe/core";
export type TextareaComponentProps = TextareaProps & {
  onModelValueChange?: (value: string) => void;
};
export function Textarea({
  modelValue = "",
  disabled = false,
  readonly = false,
  error = false,
  success = false,
  maxlength,
  onModelValueChange,
}: TextareaComponentProps) {
  return (
    <textarea
      className={`textarea${error ? " input-error" : ""}${success ? " input-success" : ""}`}
      value={modelValue}
      disabled={disabled}
      readOnly={readonly}
      maxLength={maxlength}
      onInput={(event) => onModelValueChange?.(event.currentTarget.value)}
    />
  );
}

// packages/vue/src/forms/Textarea.vue
<script setup lang="ts">
import { computed } from "vue";

import type {
  TextareaProps,
} from "@paraxe/core";

const props = withDefaults(
  defineProps<TextareaProps>(),
  {
    modelValue: "",
    disabled: false,
    readonly: false,
    error: false,
    success: false,
    maxlength: undefined,
  },
);

const emit = defineEmits<{
  "update:modelValue": [
    value: string,
  ];
}>();

const textareaClasses = computed(() => ({
  "input-error": props.error,
  "input-success": props.success,
}));

function handleInput(
  event: Event,
): void {
  const target =
    event.target as HTMLTextAreaElement;

  emit(
    "update:modelValue",
    target.value,
  );
}
</script>

<template>
  <textarea
    class="textarea"
    :class="textareaClasses"
    :value="props.modelValue"
    :disabled="props.disabled"
    :readonly="props.readonly"
    :maxlength="props.maxlength"
    @input="handleInput"
  />
</template>
