// packages/vue/src/navigation/Breadcrumb.vue
<script setup lang="ts">
import {
  computed,
  inject,
} from "vue";

import type {
  BreadcrumbsProps,
} from "@paraxe/core";

const props = withDefaults(
  defineProps<BreadcrumbsProps>(),
  {
    href: undefined,
    current: false,
  },
);

const separator = inject(
  "loba-breadcrumbs-separator",
  "/",
);

const classes = computed(() => ({
  "breadcrumbs-item": true,
}));
</script>

<template>
  <li :class="classes">
    <a
      v-if="props.href && !props.current"
      class="breadcrumbs-link"
      :href="props.href"
    >
      <slot />
    </a>

    <span
      v-else
      class="breadcrumbs-current"
      :aria-current="
        props.current
          ? 'page'
          : undefined
      "
    >
      <slot />
    </span>

    <span
      class="breadcrumbs-separator"
      aria-hidden="true"
    >
      {{ separator }}
    </span>
  </li>
</template>

// packages/react/src/navigation/Breadcrumb.tsx
import { useContext } from "react";
import type { BreadcrumbProps } from "@paraxe/core";
import type { ReactNode } from "react";
import { BreadcrumbContext } from "./Breadcrumbs";
export function Breadcrumb({
  href,
  current = false,
  children,
}: BreadcrumbProps & { children?: ReactNode }) {
  const separator = useContext(BreadcrumbContext);
  return (
    <li className="breadcrumbs-item">
      {href && !current ? (
        <a className="breadcrumbs-link" href={href}>
          {children}
        </a>
      ) : (
        <span
          className="breadcrumbs-current"
          aria-current={current ? "page" : undefined}
        >
          {children}
        </span>
      )}
      <span className="breadcrumbs-separator" aria-hidden="true">
        {separator}
      </span>
    </li>
  );
}
