// packages/vue/src/navigation/Sidebar.vue
<script setup lang="ts">
import { computed } from "vue";
import type { SidebarProps } from "@paraxe/core";

const props = withDefaults(
  defineProps<SidebarProps>(),
  {
    collapsed: false,
  },
);

const sidebarClasses = computed(() => ({
  sidebar: true,
  "sidebar--collapsed": props.collapsed,
}));
</script>

<template>
  <aside :class="sidebarClasses">
    <div class="sidebar-header">
      <slot name="header" />
    </div>

    <nav class="sidebar-navigation">
      <slot />
    </nav>

    <div class="sidebar-footer">
      <slot name="footer" />
    </div>
  </aside>
</template>

// packages/react/src/navigation/Sidebar.tsx
import type { SidebarProps } from "@paraxe/core";
import type { ReactNode } from "react";
export function Sidebar({
  collapsed = false,
  header,
  footer,
  children,
}: SidebarProps & {
  header?: ReactNode;
  footer?: ReactNode;
  children?: ReactNode;
}) {
  return (
    <aside className={`sidebar${collapsed ? " sidebar--collapsed" : ""}`}>
      <div className="sidebar-header">{header}</div>
      <nav className="sidebar-navigation">{children}</nav>
      <div className="sidebar-footer">{footer}</div>
    </aside>
  );
}
