// packages/vue/src/navigation/SidebarItem.vue
<script setup lang="ts">
import {
  computed,
  ref,
  useSlots,
} from "vue";

export interface SidebarItemProps {
  active?: boolean;
  disabled?: boolean;
  href?: string;
  expanded?: boolean;
}

const props = withDefaults(
  defineProps<SidebarItemProps>(),
  {
    active: false,
    disabled: false,
    href: undefined,
    expanded: false,
  },
);

const slots = useSlots();

const isExpanded = ref(
  props.expanded,
);

const hasChildren = computed(
  () => Boolean(slots.children),
);

const itemClasses = computed(() => ({
  "sidebar-item": true,
  "sidebar-item--active":
    props.active,
  "sidebar-item--disabled":
    props.disabled,
  "sidebar-item--expandable":
    hasChildren.value,
  "sidebar-item--expanded":
    hasChildren.value &&
    isExpanded.value,
}));

function handleClick(event: MouseEvent) {
  if (props.disabled) {
    event.preventDefault();
    return;
  }

  if (hasChildren.value) {
    event.preventDefault();
    isExpanded.value =
      !isExpanded.value;
  }
}
</script>

<template>
  <div class="sidebar-item-wrapper">
    <component
      :is="hasChildren ? 'button' : 'a'"
      :href="
        hasChildren || !props.href
          ? undefined
          : props.href
      "
      :type="
        hasChildren
          ? 'button'
          : undefined
      "
      :class="itemClasses"
      :disabled="
        hasChildren
          ? props.disabled
          : undefined
      "
      :aria-current="
        props.active
          ? 'page'
          : undefined
      "
      :aria-expanded="
        hasChildren
          ? isExpanded
          : undefined
      "
      :aria-disabled="
        props.disabled
          ? 'true'
          : undefined
      "
      @click="handleClick"
    >
      <span
        v-if="$slots.icon"
        class="sidebar-item-icon"
        aria-hidden="true"
      >
        <slot name="icon" />
      </span>

      <span class="sidebar-item-label">
        <slot />
      </span>

      <span
        v-if="hasChildren"
        class="sidebar-item-chevron"
        aria-hidden="true"
      >
        <span
          :class="{
            'sidebar-item-chevron--expanded':
              isExpanded,
          }"
        >
          ›
        </span>
      </span>
    </component>

    <div
      v-if="
        hasChildren &&
        isExpanded
      "
      class="sidebar-item-children"
    >
      <slot name="children" />
    </div>
  </div>
</template>

// packages/react/src/navigation/SidebarItem.tsx
import { useState } from "react";
import type { ReactNode } from "react";
export function SidebarItem({
  active = false,
  disabled = false,
  href,
  expanded = false,
  icon,
  childItems,
  children,
}: {
  active?: boolean;
  disabled?: boolean;
  href?: string;
  expanded?: boolean;
  icon?: ReactNode;
  childItems?: ReactNode;
  children?: ReactNode;
}) {
  const [open, setOpen] = useState(expanded);
  const hasChildren = childItems != null;
  const cls = `sidebar-item${active ? " sidebar-item--active" : ""}${disabled ? " sidebar-item--disabled" : ""}${hasChildren ? " sidebar-item--expandable" : ""}${hasChildren && open ? " sidebar-item--expanded" : ""}`;
  const content = (
    <>
      <span className="sidebar-item-icon" aria-hidden="true">
        {icon}
      </span>
      <span className="sidebar-item-label">{children}</span>
      {hasChildren ? (
        <span className="sidebar-item-chevron" aria-hidden="true">
          <span className={open ? "sidebar-item-chevron--expanded" : undefined}>
            ›
          </span>
        </span>
      ) : null}
    </>
  );
  return (
    <div className="sidebar-item-wrapper">
      {hasChildren ? (
        <button
          type="button"
          className={cls}
          disabled={disabled}
          aria-current={active ? "page" : undefined}
          aria-expanded={open}
          onClick={() => setOpen(!open)}
        >
          {content}
        </button>
      ) : (
        <a
          className={cls}
          href={href}
          aria-current={active ? "page" : undefined}
          aria-disabled={disabled || undefined}
          onClick={(e) => disabled && e.preventDefault()}
        >
          {content}
        </a>
      )}
      {hasChildren && open ? (
        <div className="sidebar-item-children">{childItems}</div>
      ) : null}
    </div>
  );
}
