// packages/vue/src/composites/AccordionItem.vue
<script setup lang="ts">
import { computed, inject } from "vue";

import type { AccordionItemProps } from "@paraxe/core";

const props = withDefaults(defineProps<AccordionItemProps>(), {
  disabled: false,
});

type AccordionContext = {
  isOpen: (id: string) => boolean;
  toggleItem: (id: string) => void;
};
const injectedAccordion = inject<AccordionContext>("loba-accordion");

if (!injectedAccordion) {
  throw new Error(
    "AccordionItem must be used inside an Accordion.",
  );
}

const accordion = injectedAccordion;

if (!accordion) {
  throw new Error(
    "AccordionItem must be used inside an Accordion.",
  );
}

const isOpen = computed(() => accordion.isOpen(props.id));

function toggle() {
  if (!props.disabled) {
    accordion.toggleItem(props.id);
  }
}
</script>

<template>
  <div
    class="accordion-item"
    :class="{ 'accordion-item--open': isOpen }"
  >
    <button
      type="button"
      class="accordion-trigger"
      :disabled="props.disabled"
      :aria-expanded="isOpen"
      :aria-controls="`accordion-${props.id}`"
      @click="toggle"
    >
      <slot name="trigger" />
    </button>

    <div
      v-show="isOpen"
      :id="`accordion-${props.id}`"
      class="accordion-content"
    >
      <slot />
    </div>
  </div>
</template>

// packages/react/src/composites/AccordionItem.tsx
import type { AccordionItemProps } from "@paraxe/core";
import type { ReactNode } from "react";
import { useAccordion } from "./Accordion";
export function AccordionItem({
  id,
  disabled = false,
  trigger,
  children,
}: AccordionItemProps & { trigger?: ReactNode; children?: ReactNode }) {
  const accordion = useAccordion();
  if (!accordion)
    throw new Error("AccordionItem must be used inside an Accordion.");
  const open = accordion.isOpen(id);
  return (
    <div className={`accordion-item${open ? " accordion-item--open" : ""}`}>
      <button
        type="button"
        className="accordion-trigger"
        disabled={disabled}
        aria-expanded={open}
        aria-controls={`accordion-${id}`}
        onClick={() => !disabled && accordion.toggleItem(id)}
      >
        {trigger}
      </button>
      <div id={`accordion-${id}`} className="accordion-content" hidden={!open}>
        {children}
      </div>
    </div>
  );
}
