// packages/vue/src/composites/ButtonGroup.vue
<script setup lang="ts">
import { computed } from "vue";

type ButtonGroupAlign = "start" | "center" | "end";

interface Props {
  align?: ButtonGroupAlign;
  stack?: boolean;
}

const props = withDefaults(defineProps<Props>(), {
  align: "start",
  stack: false,
});

const buttonGroupClasses = computed(() => ({
  "button-group--center": props.align === "center",
  "button-group--end": props.align === "end",
  "button-group--stack": props.stack,
}));
</script>

<template>
  <div class="button-group" :class="buttonGroupClasses">
    <slot />
  </div>
</template>

// packages/react/src/composites/ButtonGroup.tsx
import type { ButtonGroupProps } from "@paraxe/core";
import type { ReactNode } from "react";
export function ButtonGroup({
  align = "start",
  stack = false,
  children,
}: ButtonGroupProps & { children?: ReactNode }) {
  return (
    <div
      className={`button-group${align === "center" ? " button-group--center" : align === "end" ? " button-group--end" : ""}${stack ? " button-group--stack" : ""}`}
    >
      {children}
    </div>
  );
}
