// packages/vue/src/media/Image.vue
<script setup lang="ts">
import type {
  ImageProps,
} from "@paraxe/core";


const props = withDefaults(defineProps<ImageProps>(), {
  fit: "cover",
  aspectRatio: "auto",
});
</script>

<template>
  <div
    class="media"
    :class="{
      'media-square': props.aspectRatio === 'square',
      'media-video': props.aspectRatio === 'video',
      'media-portrait': props.aspectRatio === 'portrait',
      'media-wide': props.aspectRatio === 'wide',
      'media-contain': props.fit === 'contain',
    }"
  >
    <img
      :src="props.src"
      :alt="props.alt"
    />
  </div>
</template>

// packages/react/src/media/Image.tsx
import type { ImageProps } from "@paraxe/core";
export function Image({
  src,
  alt,
  fit = "cover",
  aspectRatio = "auto",
}: ImageProps) {
  return (
    <div
      className={`media${aspectRatio === "auto" ? "" : ` media-${aspectRatio}`}${fit === "contain" ? " media-contain" : ""}`}
    >
      <img src={src} alt={alt} />
    </div>
  );
}
