// packages/vue/src/forms/Input.vue
<script setup lang="ts">
import { computed } from "vue";
import type { InputType } from "@paraxe/core";

interface Props {
  type?: InputType;
  placeholder?: string;
  modelValue?: string;
  required?: boolean;
  disabled?: boolean;
  readonly?: boolean;
  error?: boolean;
  success?: boolean;
}

const props = withDefaults(defineProps<Props>(), {
  type: "text",
  placeholder: "",
  modelValue: "",
  required: false,
  disabled: false,
  readonly: false,
  error: false,
  success: false,
});

const emit = defineEmits<{
  "update:modelValue": [value: string];
}>();

const inputClasses = computed(() => ({
  "input-error": props.error,
  "input-success": props.success,
}));

function handleInput(event: Event): void {
  emit(
    "update:modelValue",
    (event.target as HTMLInputElement).value,
  );
}
</script>

<template>
  <input
    :class="['input', inputClasses]"
    :type="props.type"
    :placeholder="props.placeholder"
    :value="props.modelValue"
    :required="props.required"
    :disabled="props.disabled"
    :readonly="props.readonly"
    @input="handleInput"
  />
</template>

// packages/react/src/forms/Input.tsx
import type { InputProps } from "@paraxe/core";
export type InputComponentProps = InputProps & {
  onModelValueChange?: (value: string) => void;
};
export function Input({
  type = "text",
  placeholder = "",
  modelValue = "",
  required = false,
  disabled = false,
  readonly = false,
  error = false,
  success = false,
  onModelValueChange,
}: InputComponentProps) {
  return (
    <input
      className={`input${error ? " input-error" : ""}${success ? " input-success" : ""}`}
      type={type}
      placeholder={placeholder}
      value={modelValue}
      required={required}
      disabled={disabled}
      readOnly={readonly}
      onInput={(event) => onModelValueChange?.(event.currentTarget.value)}
    />
  );
}
