// packages/vue/src/forms/Radio.vue
<script setup lang="ts">
import { computed } from "vue";

import type {
  RadioProps,
} from "@paraxe/core";

const props = withDefaults(
  defineProps<RadioProps>(),
  {
    modelValue: null,
    disabled: false,
  },
);

const emit = defineEmits<{
  "update:modelValue": [
    value: string | number,
  ];
}>();

const checked = computed(
  () =>
    props.modelValue ===
    props.value,
);

const classes = computed(() => ({
  radio: true,
  "radio--checked":
    checked.value,
  "radio--disabled":
    props.disabled,
}));

function handleChange() {
  emit(
    "update:modelValue",
    props.value,
  );
}
</script>

<template>
  <label :class="classes">
    <input
      type="radio"
      :name="name"
      :value="value"
      :checked="checked"
      :disabled="disabled"
      class="sr-only"
      @change="handleChange"
    />

    <span
      class="radio-control"
      aria-hidden="true"
    />

    <span>
      <slot />
    </span>
  </label>
</template>

// packages/react/src/forms/Radio.tsx
import type { RadioProps } from "@paraxe/core";
import type { ReactNode } from "react";
export type RadioComponentProps = RadioProps & {
  children?: ReactNode;
  onModelValueChange?: (value: string | number) => void;
};
export function Radio({
  modelValue = null,
  value,
  name,
  disabled = false,
  onModelValueChange,
  children,
}: RadioComponentProps) {
  const checked = modelValue === value;
  return (
    <label
      className={`radio${checked ? " radio--checked" : ""}${disabled ? " radio--disabled" : ""}`}
    >
      <input
        type="radio"
        name={name}
        value={value}
        checked={checked}
        disabled={disabled}
        className="sr-only"
        onChange={() => onModelValueChange?.(value)}
      />
      <span className="radio-control" aria-hidden="true" />
      <span>{children}</span>
    </label>
  );
}
