// packages/vue/src/forms/Select.vue
<script setup lang="ts">
import { computed } from "vue";

import type {
  SelectProps,
} from "@paraxe/core";

const props = withDefaults(
  defineProps<SelectProps>(),
  {
    modelValue: "",
    disabled: false,
    error: false,
    success: false,
  },
);

const emit = defineEmits<{
  "update:modelValue": [
    value: string,
  ];
}>();

function handleChange(
  event: Event,
) {
  const target =
    event.target as HTMLSelectElement;

  emit(
    "update:modelValue",
    target.value,
  );
}

const selectClasses = computed(() => ({
  "input-error": props.error,
  "input-success": props.success,
}));
</script>

<template>
 <select
  class="select"
  :class="selectClasses"
  :value="props.modelValue"
  :disabled="props.disabled"
  @change="handleChange"
>
  <slot />
</select>
</template>

// packages/react/src/forms/Select.tsx
import type { SelectProps } from "@paraxe/core";
import type { ReactNode } from "react";
export type SelectComponentProps = SelectProps & {
  children?: ReactNode;
  onModelValueChange?: (value: string) => void;
};
export function Select({
  modelValue = "",
  disabled = false,
  error = false,
  success = false,
  onModelValueChange,
  children,
}: SelectComponentProps) {
  return (
    <select
      className={`select${error ? " input-error" : ""}${success ? " input-success" : ""}`}
      value={modelValue}
      disabled={disabled}
      onChange={(event) => onModelValueChange?.(event.currentTarget.value)}
    >
      {children}
    </select>
  );
}
