// packages/vue/src/forms/Switch.vue
<script setup lang="ts">
import { computed } from "vue";

import type {
  SwitchProps,
} from "@paraxe/core";

const props = withDefaults(
  defineProps<SwitchProps>(),
  {
    modelValue: false,
    disabled: false,
  },
);

const emit = defineEmits<{
  "update:modelValue": [
    value: boolean,
  ];
}>();

const classes = computed(() => ({
  switch: true,
  "switch--checked":
    props.modelValue,
  "switch--disabled":
    props.disabled,
}));

function handleChange(
  event: Event,
) {
  const input =
    event.target as HTMLInputElement;

  emit(
    "update:modelValue",
    input.checked,
  );
}
</script>
<template>
  <label :class="classes">
    <input
      type="checkbox"
      role="switch"
      :checked="modelValue"
      :disabled="disabled"
      class="sr-only"
      @change="handleChange"
    />

    <span
      class="switch-control"
      aria-hidden="true"
    />

    <span>
      <slot />
    </span>
  </label>
</template>

// packages/react/src/forms/Switch.tsx
import type { SwitchProps } from "@paraxe/core";
import type { ReactNode } from "react";
export type SwitchComponentProps = SwitchProps & {
  children?: ReactNode;
  onModelValueChange?: (value: boolean) => void;
};
export function Switch({
  modelValue = false,
  disabled = false,
  onModelValueChange,
  children,
}: SwitchComponentProps) {
  return (
    <label
      className={`switch${modelValue ? " switch--checked" : ""}${disabled ? " switch--disabled" : ""}`}
    >
      <input
        type="checkbox"
        role="switch"
        checked={modelValue}
        disabled={disabled}
        className="sr-only"
        onChange={(event) => onModelValueChange?.(event.currentTarget.checked)}
      />
      <span className="switch-control" aria-hidden="true" />
      <span>{children}</span>
    </label>
  );
}
