// packages/react/src/navigation/Tab.tsx
import type { TabProps } from "@paraxe/core";
import type { ReactNode } from "react";
import { useTabs } from "./Tabs";
export function Tab({
  value,
  disabled = false,
  children,
}: TabProps & { children?: ReactNode }) {
  const tabs = useTabs();
  if (!tabs) throw new Error("Tab must be used inside Tabs.");
  const active = tabs.active === value;
  return (
    <button
      type="button"
      className={`tab${active ? " tab--active" : ""}${disabled ? " tab--disabled" : ""}`}
      role="tab"
      aria-selected={active}
      aria-disabled={disabled || undefined}
      tabIndex={active ? 0 : -1}
      onClick={() => !disabled && tabs.select(value)}
    >
      {children}
    </button>
  );
}

// packages/vue/src/navigation/Tab.vue
<script setup lang="ts">
import {
  computed,
  inject,
} from "vue";
import type { TabProps } from "@paraxe/core";

const props = withDefaults(
  defineProps<TabProps>(),
  {
    disabled: false,
  },
);

interface TabsContext {
  activeValue: () =>
    | string
    | number
    | null;
  selectTab: (
    value: string | number,
  ) => void;
}

const injectedTabs =
  inject<TabsContext>("loba-tabs");

if (!injectedTabs) {
  throw new Error(
    "Tab must be used inside Tabs.",
  );
}

const tabs = injectedTabs;

const active = computed(
  () =>
    tabs.activeValue() ===
    props.value,
);

const tabClasses = computed(() => ({
  tab: true,
  "tab--active": active.value,
  "tab--disabled": props.disabled,
}));

function handleClick() {
  if (props.disabled) {
    return;
  }

  tabs.selectTab(props.value);
}
</script>

<template>
  <button
    type="button"
    :class="tabClasses"
    role="tab"
    :aria-selected="active"
    :aria-disabled="
      props.disabled || undefined
    "
    :tabindex="
      active ? 0 : -1
    "
    @click="handleClick"
  >
    <slot />
  </button>
</template>
