// packages/react/src/composites/Accordion.tsx
import { createContext, useContext, useState } from "react";
import type { AccordionProps } from "@paraxe/core";
import type { ReactNode } from "react";
const AccordionContext = createContext<{
  isOpen: (id: string) => boolean;
  toggleItem: (id: string) => void;
} | null>(null);
export function Accordion({
  multiple = false,
  collapsible = true,
  defaultOpen = [],
  children,
}: AccordionProps & { children?: ReactNode }) {
  const [open, setOpen] = useState(defaultOpen);
  const toggleItem = (id: string) =>
    setOpen((current) =>
      current.includes(id)
        ? collapsible
          ? current.filter((item) => item !== id)
          : current
        : multiple
          ? [...current, id]
          : [id],
    );
  return (
    <AccordionContext.Provider
      value={{ isOpen: (id) => open.includes(id), toggleItem }}
    >
      <div className="accordion">{children}</div>
    </AccordionContext.Provider>
  );
}
export function useAccordion() {
  return useContext(AccordionContext);
}

// packages/vue/src/composites/Accordion.vue
<script setup lang="ts">
import { provide, ref, computed } from "vue";
import type { AccordionProps } from "@paraxe/core"

type AccordionContext = {
  openItems: Readonly<ReturnType<typeof ref<string[]>>>;
  isOpen: (id: string) => boolean;
  toggleItem: (id: string) => void;
};

const props = withDefaults(
  defineProps<AccordionProps
  >(),
  {
    multiple: false,
    collapsible: true,
    defaultOpen: () => [],
  },
);

const openItems = ref<string[]>([...props.defaultOpen]);

function isOpen(id: string) {
  return openItems.value.includes(id);
}

function toggleItem(id: string) {
  const currentlyOpen = isOpen(id);

  if (currentlyOpen) {
    if (!props.collapsible) {
      return;
    }

    openItems.value = openItems.value.filter((item) => item !== id);
    return;
  }

  if (props.multiple) {
    openItems.value = [...openItems.value, id];
    return;
  }

  openItems.value = [id];
}

provide("loba-accordion", {
  openItems,
  isOpen,
  toggleItem,
} satisfies AccordionContext);
</script>

<template>
  <div class="accordion">
    <slot />
  </div>
</template>
