// packages/vue/src/overlays/Tooltip.vue
<script setup lang="ts">
import {
  onBeforeUnmount,
  ref,
} from "vue";
import type {
  TooltipProps,
} from "@paraxe/core";

const props = withDefaults(
  defineProps<TooltipProps>(),
  {
    placement: "top",
    delay: 300,
  },
);

const visible = ref(false);

let timer:
  | ReturnType<typeof setTimeout>
  | undefined;

function show() {
  clearTimeout(timer);

  timer = setTimeout(() => {
    visible.value = true;
  }, props.delay);
}

function hide() {
  clearTimeout(timer);
  visible.value = false;
}

onBeforeUnmount(() => {
  clearTimeout(timer);
});
</script>

<template>
  <span
    class="tooltip"
    :class="{
      'tooltip--visible': visible,
      [`tooltip--${props.placement}`]:
        true,
    }"
    @mouseenter="show"
    @mouseleave="hide"
    @focusin="show"
    @focusout="hide"
  >
    <span class="tooltip-trigger">
      <slot />
    </span>

    <span
      class="tooltip-content"
      role="tooltip"
    >
      {{ props.text }}
    </span>
  </span>
</template>

// packages/react/src/overlays/Tooltip.tsx
import { useEffect, useRef, useState } from "react";
import type { TooltipProps } from "@paraxe/core";
import type { ReactNode } from "react";
export function Tooltip({
  text,
  placement = "top",
  delay = 300,
  children,
}: TooltipProps & { children?: ReactNode }) {
  const [visible, setVisible] = useState(false),
    timer = useRef<ReturnType<typeof setTimeout> | undefined>(undefined);
  const show = () => {
    clearTimeout(timer.current);
    timer.current = setTimeout(() => setVisible(true), delay);
  };
  const hide = () => {
    clearTimeout(timer.current);
    setVisible(false);
  };
  useEffect(() => () => clearTimeout(timer.current), []);
  return (
    <span
      className={`tooltip${visible ? " tooltip--visible" : ""} tooltip--${placement}`}
      onMouseEnter={show}
      onMouseLeave={hide}
      onFocus={show}
      onBlur={hide}
    >
      <span className="tooltip-trigger">{children}</span>
      <span className="tooltip-content" role="tooltip">
        {text}
      </span>
    </span>
  );
}
