// packages/react/src/data/Table.tsx
import { useState } from "react";
import type { ReactNode } from "react";
import type { TableColumn, TableProps } from "@paraxe/core";
export type TableComponentProps<T> = TableProps<T> & {
  onSelectedRowsChange?: (rows: T[]) => void;
  onSort?: (payload: { key: string; direction: "asc" | "desc" }) => void;
  onRowClick?: (row: T) => void;
  renderCell?: (column: TableColumn<T>, row: T, value: unknown) => ReactNode;
};
export function Table<T>({
  columns,
  rows,
  rowKey = "id",
  sortable = false,
  selectable = false,
  multiple = false,
  loading = false,
  onSelectedRowsChange,
  onSort,
  onRowClick,
  renderCell,
}: TableComponentProps<T>) {
  const [sort, setSort] = useState<{
    key: string;
    direction: "asc" | "desc";
  } | null>(null);
  const [selected, setSelected] = useState<Set<string | number>>(new Set());
  const value = (row: T, key: string) =>
    row && typeof row === "object"
      ? (row as Record<string, unknown>)[key]
      : undefined;
  const key = (row: T) => {
    const v = value(row, rowKey);
    return typeof v === "string" || typeof v === "number"
      ? v
      : rows.indexOf(row);
  };
  const sorted =
    !sortable || !sort
      ? rows
      : [...rows].sort((a, b) => {
          const av = value(a, sort.key),
            bv = value(b, sort.key);
          const r =
            av == null
              ? 1
              : bv == null
                ? -1
                : typeof av === "number" && typeof bv === "number"
                  ? av - bv
                  : String(av).localeCompare(String(bv), undefined, {
                      numeric: true,
                      sensitivity: "base",
                    });
          return sort.direction === "asc" ? r : -r;
        });
  const toggleSort = (c: TableColumn<T>) => {
    if (!sortable || !c.sortable) return;
    const next =
      sort?.key === c.key
        ? {
            key: c.key,
            direction:
              sort.direction === "asc" ? ("desc" as const) : ("asc" as const),
          }
        : { key: c.key, direction: "asc" as const };
    setSort(next);
    onSort?.(next);
  };
  const click = (row: T) => {
    if (selectable) {
      const next = new Set(selected),
        k = key(row);
      if (multiple) next.has(k) ? next.delete(k) : next.add(k);
      else {
        next.clear();
        next.add(k);
      }
      setSelected(next);
      onSelectedRowsChange?.(rows.filter((item) => next.has(key(item))));
    }
    onRowClick?.(row);
  };
  return (
    <div className="table">
      <table>
        <thead>
          <tr>
            {columns.map((c) => (
              <th
                key={c.key}
                style={{ width: c.width }}
                className={`table-cell--${c.align ?? "start"}${sortable && c.sortable ? " table-header--sortable" : ""}${sort?.key === c.key ? " table-header--sorted" : ""}`}
                tabIndex={sortable && c.sortable ? 0 : undefined}
                aria-sort={
                  sort?.key === c.key
                    ? sort.direction === "asc"
                      ? "ascending"
                      : "descending"
                    : undefined
                }
                onClick={() => toggleSort(c)}
                onKeyDown={(e) => {
                  if (e.key === "Enter" || e.key === " ") {
                    e.preventDefault();
                    toggleSort(c);
                  }
                }}
              >
                <span>{c.label}</span>
                {sortable && c.sortable ? (
                  <span aria-hidden="true">
                    {sort?.key === c.key
                      ? sort.direction === "asc"
                        ? "↑"
                        : "↓"
                      : ""}
                  </span>
                ) : null}
              </th>
            ))}
          </tr>
        </thead>
        <tbody>
          {sorted.map((row) => (
            <tr
              key={key(row)}
              className={`${selected.has(key(row)) ? "table-row--selected " : ""}table-row--clickable`}
              onClick={() => click(row)}
            >
              {columns.map((c) => {
                const v = value(row, c.key);
                return (
                  <td
                    key={c.key}
                    className={`table-cell--${c.align ?? "start"}`}
                  >
                    {renderCell
                      ? renderCell(c, row, v)
                      : c.render
                        ? String(c.render(v, row) ?? "")
                        : String(v ?? "")}
                  </td>
                );
              })}
            </tr>
          ))}
        </tbody>
      </table>
      {loading ? <div className="table-loading" aria-hidden="true" /> : null}
    </div>
  );
}

// packages/vue/src/data/Table.vue
```vue
<script setup lang="ts">
import {
  computed,
  ref,
} from "vue";

export interface TableColumn<T = unknown> {
  key: string;
  label: string;
  sortable?: boolean;
  width?: string;
  align?: "start" | "center" | "end";
}

export interface TableProps<T = unknown> {
  columns: TableColumn<T>[];
  rows: T[];
  rowKey?: string;
  sortable?: boolean;
  selectable?: boolean;
  multiple?: boolean;
  loading?: boolean;
}

const props = withDefaults(
  defineProps<TableProps>(),
  {
    rowKey: "id",
    sortable: false,
    selectable: false,
    multiple: false,
    loading: false,
  },
);

const emit = defineEmits<{
  "update:selectedRows": [
    rows: unknown[],
  ];
  sort: [
    payload: {
      key: string;
      direction: "asc" | "desc";
    },
  ];
  "row-click": [row: unknown];
}>();

const sortKey = ref<string | null>(null);

const sortDirection = ref<
  "asc" | "desc"
>("asc");

const selectedKeys = ref<
  Set<string | number>
>(new Set());

function getRowValue(
  row: unknown,
  key: string,
) {
  if (
    typeof row !== "object" ||
    row === null
  ) {
    return undefined;
  }

  return (
    row as Record<
      string,
      unknown
    >
  )[key];
}

function getRowKey(
  row: unknown,
): string | number {
  const value = getRowValue(
    row,
    props.rowKey,
  );

  if (
    typeof value === "string" ||
    typeof value === "number"
  ) {
    return value;
  }

  return props.rows.indexOf(row);
}

function isSelected(
  row: unknown,
): boolean {
  return selectedKeys.value.has(
    getRowKey(row),
  );
}

const sortedRows = computed(() => {
  if (
    !props.sortable ||
    !sortKey.value
  ) {
    return props.rows;
  }

  const key = sortKey.value;
  const direction =
    sortDirection.value;

  return [...props.rows].sort(
    (a, b) => {
      const aValue =
        getRowValue(a, key);

      const bValue =
        getRowValue(b, key);

      if (aValue === bValue) {
        return 0;
      }

      if (
        aValue === undefined ||
        aValue === null
      ) {
        return 1;
      }

      if (
        bValue === undefined ||
        bValue === null
      ) {
        return -1;
      }

      if (
        typeof aValue === "number" &&
        typeof bValue === "number"
      ) {
        return direction === "asc"
          ? aValue - bValue
          : bValue - aValue;
      }

      const result =
        String(aValue).localeCompare(
          String(bValue),
          undefined,
          {
            numeric: true,
            sensitivity: "base",
          },
        );

      return direction === "asc"
        ? result
        : -result;
    },
  );
});

function toggleSort(
  column: TableColumn,
): void {
  if (
    !props.sortable ||
    !column.sortable
  ) {
    return;
  }

  if (
    sortKey.value !== column.key
  ) {
    sortKey.value = column.key;
    sortDirection.value = "asc";
  } else {
    sortDirection.value =
      sortDirection.value === "asc"
        ? "desc"
        : "asc";
  }

  emit("sort", {
    key: column.key,
    direction:
      sortDirection.value,
  });
}

function toggleRowSelection(
  row: unknown,
): void {
  if (!props.selectable) {
    return;
  }

  const key = getRowKey(row);

  const next = new Set(
    selectedKeys.value,
  );

  if (props.multiple) {
    if (next.has(key)) {
      next.delete(key);
    } else {
      next.add(key);
    }
  } else {
    next.clear();
    next.add(key);
  }

  selectedKeys.value = next;

  emit(
    "update:selectedRows",
    props.rows.filter((item) =>
      next.has(getRowKey(item)),
    ),
  );
}

function handleRowClick(
  row: unknown,
): void {
  if (props.selectable) {
    toggleRowSelection(row);
  }

  emit("row-click", row);
}

function sortIndicator(
  column: TableColumn,
): string {
  if (
    sortKey.value !== column.key
  ) {
    return "";
  }

  return sortDirection.value ===
    "asc"
    ? "↑"
    : "↓";
}

function cellClass(
  column: TableColumn,
) {
  return {
    [`table-cell--${
      column.align ?? "start"
    }`]: true,
  };
}

function isSorted(
  column: TableColumn,
): boolean {
  return (
    sortKey.value === column.key
  );
}
</script>

<template>
  <div class="table">
    <table>
      <thead>
        <tr>
          <th
            v-for="column in columns"
            :key="column.key"
            :style="{
              width: column.width,
            }"
            :class="[
              cellClass(column),
              {
                'table-header--sortable':
                  sortable &&
                  column.sortable,
                'table-header--sorted':
                  isSorted(column),
              },
            ]"
            :tabindex="
              sortable &&
              column.sortable
                ? 0
                : undefined
            "
            :aria-sort="
              isSorted(column)
                ? sortDirection ===
                  'asc'
                  ? 'ascending'
                  : 'descending'
                : undefined
            "
            @click="
              toggleSort(column)
            "
            @keydown.enter="
              toggleSort(column)
            "
            @keydown.space.prevent="
              toggleSort(column)
            "
          >
            <span>
              {{ column.label }}
            </span>

            <span
              v-if="
                sortable &&
                column.sortable
              "
              aria-hidden="true"
            >
              {{
                sortIndicator(column)
              }}
            </span>
          </th>
        </tr>
      </thead>

      <tbody>
        <tr
          v-for="row in sortedRows"
          :key="getRowKey(row)"
          :class="{
            'table-row--selected':
              isSelected(row),
            'table-row--clickable': true,
          }"
          @click="
            handleRowClick(row)
          "
        >
          <td
            v-for="column in columns"
            :key="column.key"
            :class="
              cellClass(column)
            "
          >
            <slot
              :name="
                `cell-${column.key}`
              "
              :row="row"
              :value="
                getRowValue(
                  row,
                  column.key,
                )
              "
            >
              {{
                getRowValue(
                  row,
                  column.key,
                )
              }}
            </slot>
          </td>
        </tr>
      </tbody>
    </table>

    <div
      v-if="loading"
      class="table-loading"
      aria-hidden="true"
    />
  </div>
</template>

<Table
  :columns="columns"
  :rows="currentPageProspects"
  row-key="id"
  sortable
  @row-click="openProspect"
/>
