// packages/vue/src/typography/Label.vue
<script setup lang="ts">
import { computed } from "vue";

interface Props {
  for?: string;
  required?: boolean;
  optional?: boolean;
  disabled?: boolean;
}

const props = withDefaults(defineProps<Props>(), {
  for: undefined,
  required: false,
  optional: false,
  disabled: false,
});

const labelClasses = computed(() => ({
  "label-disabled": props.disabled,
}));
</script>

<template>
  <label
    :for="props.for"
    class="label"
    :class="labelClasses"
  >
    <slot />

    <span v-if="props.required" aria-hidden="true">*</span>
    <span v-else-if="props.optional">(optional)</span>
  </label>
</template>

// packages/react/src/typography/Label.tsx
import type { LabelProps } from "@paraxe/core";
import type { ReactNode } from "react";
export type LabelComponentProps = LabelProps & { children?: ReactNode };
export function Label({
  for: htmlFor,
  required = false,
  optional = false,
  disabled = false,
  children,
}: LabelComponentProps) {
  return (
    <label
      htmlFor={htmlFor}
      className={`label${disabled ? " label-disabled" : ""}`}
    >
      {children}
      {required ? (
        <span aria-hidden="true">*</span>
      ) : optional ? (
        <span> (optional)</span>
      ) : null}
    </label>
  );
}
