// packages/vue/src/feedback/Skeleton.vue
<script setup lang="ts">
import { computed } from "vue";

import type {
  SkeletonProps,
} from "@paraxe/core";

const props = withDefaults(
  defineProps<SkeletonProps>(),
  {
    variant: "default",
    width: undefined,
    height: undefined,
  },
);

const skeletonClasses = computed(() => ({
  skeleton: true,
  [`skeleton--${props.variant}`]:
    props.variant !== "default",
}));
</script>

<template>
  <div
    :class="skeletonClasses"
    :style="{
      width: props.width,
      height: props.height,
    }"
    aria-hidden="true"
  />
</template>

// packages/react/src/feedback/Skeleton.tsx
import type { SkeletonProps } from "@paraxe/core";
export function Skeleton({
  variant = "default",
  width,
  height,
}: SkeletonProps) {
  return (
    <div
      className={`skeleton${variant === "default" ? "" : ` skeleton--${variant}`}`}
      style={{ width, height }}
      aria-hidden="true"
    />
  );
}
