// packages/react/src/typography/Heading.tsx
import type { HeadingProps } from "@paraxe/core";
import type { ReactNode } from "react";
export type HeadingComponentProps = HeadingProps & { children?: ReactNode };
export function Heading({ level = "h2", children }: HeadingComponentProps) {
  const Tag = level;
  const size =
    level === "h1"
      ? "heading-xl"
      : level === "h2"
        ? "heading-lg"
        : level === "h3"
          ? "heading-md"
          : level === "h4"
            ? "heading-sm"
            : "heading-xs";
  return <Tag className={size}>{children}</Tag>;
}

// packages/vue/src/typography/Heading.vue
<script setup lang="ts">
import { computed } from "vue";
import type { HeadingProps } from "@paraxe/core";

const props = withDefaults(
  defineProps<HeadingProps>(),
  {
    level: "h2",
  },
);

const headingClasses = computed(() => ({
  "heading-xl": props.level === "h1",
  "heading-lg": props.level === "h2",
  "heading-md": props.level === "h3",
  "heading-sm": props.level === "h4",
  "heading-xs":
    props.level === "h5" ||
    props.level === "h6",
}));
</script>

<template>
  <component
    :is="props.level"
    :class="headingClasses"
  >
    <slot />
  </component>
</template>
